{"cells":[{"cell_type":"markdown","metadata":{"tags":["raises-exception"],"id":"79c36QWnh5CF"},"source":["# Dealing with errors\n","\n","---\n","\n","##General information\n","**Sources**\n","\n","This lesson is inspired by the Geo-python module at the University of Helsinki which in turn acknowledges the Programming in Python lessons from the Software Carpentry organization. This version was adapted for Colab and a UK context by Ruth Hamilton.\n","\n","**About this document**\n","\n","This is a Google Colab Notebook. This particular notebook is designed to introduce you to a few of the basic concepts of programming in Python. Like other common notebook formats (e.g. Jupyter), the contents of this document are divided into cells, which can contain:\n","\n","Markdown-formatted text,\n","Python code, or\n","raw text\n","You can execute a snippet of code in a cell by pressing Shift-Enter or by pressing the Run Cell button that appears when your cursor is on the cell .\n","\n","---\n","\n","## Interpreting error messages\n","\n","So far in the course we have encountered a number of different types of error messages in Python, but have not really discussed how to understand what the computer is trying to tell you when you get an error message.\n","We'll do that below.\n","For most Python errors you will see and exception raised when the error is encountered, providing some insight into what went wrong and where to look to fix it."]},{"cell_type":"markdown","metadata":{"id":"p64Ygw6Lh5CK"},"source":["### Reading error messages\n","\n","Let's imagine you've written the code below called to convert wind speeds from km/hr to m/s and you're dying to figure out how windy it is in [Halifax, Nova Scotia, Canada](https://www.theweathernetwork.com/ca/weather/nova-scotia/halifax) where they report wind speeds in km/hr.\n","\n","Unfortunately, when you run your script you observe the following:"]},{"cell_type":"code","execution_count":null,"metadata":{"tags":["raises-exception"],"id":"zPFpaaYfh5CL"},"outputs":[],"source":["wind_speed_km = 50\n","wind_speed_ms = wind_speed_km * 1000 / 3600\n","\n","print(f'A wind speed of {wind_speed_km} km/hr is {wind_speed_ms} m/s.)"]},{"cell_type":"markdown","metadata":{"id":"hSHa7rWfh5CM"},"source":["Let's break this example down and see what the error message says.\n","\n","Firstly, we can see that the error was on `line 4`.\n","\n","We also have the **type** of error, a `SyntaxError` in this case, as well as an indication about where it occurred on the line (indicated by the `^`). The location given by the line number is not always correct, but Python makes its best guess for where you should look to solve the problem. Clearly, this is handy information.\n","\n","The error in this example is one of the most common - we haven't 'closed' the quotation marks around our text.\n","\n"]},{"cell_type":"code","source":["#see if you can fix the error in the code below:\n","wind_speed_km = 50\n","wind_speed_ms = wind_speed_km * 1000 / 3600\n","\n","print(f'A wind speed of {wind_speed_km} km/hr is {wind_speed_ms} m/s.)"],"metadata":{"id":"caz3vs56jvha"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["#@title Click below to show the fixed code:\n","#see if you can fix the error in the code below:\n","wind_speed_km = 50\n","wind_speed_ms = wind_speed_km * 1000 / 3600\n","\n","print(f'A wind speed of {wind_speed_km} km/hr is {wind_speed_ms} m/s.)"],"metadata":{"cellView":"form","id":"dl_JdeCNkTMu"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["Let's consider another example, where you have fixed the `SyntaxError` above and now have made a function for calculating a wind speeds in m/s.\n","\n","When you run this script you encounter a new and bigger error message:"],"metadata":{"id":"4AM3ZIyhj0nU"}},{"cell_type":"code","execution_count":null,"metadata":{"tags":["raises-exception"],"id":"XvHa8o9Ch5CN"},"outputs":[],"source":["def convert_wind_speed(speed):\n","    return speed * 1000 / 3600\n","\n","wind_speed_km = '30'\n","wind_speed_ms = convert_wind_speed(wind_speed_km)\n","\n","print(f'A wind speed of {wind_speed_km} km/hr is {wind_speed_ms} m/s.')"]},{"cell_type":"markdown","metadata":{"id":"EYTsMZsBh5CN"},"source":["In this case we see a `TypeError` that is part of a *traceback*, where the problem in the code arises from something other than on the line where the code was run.\n","\n","In this case, we have a `TypeError` where we try to divide a character string by a number, something Python cannot do. Hence, the `TypeError` indicating the data **types** are not compatible. That error, however, does not occur when the code is run until the point where the function is used. Thus, we see the traceback showing that not only does the error occur when the function is called, but also that the problem is in the function definition.\n","\n","The traceback above may look a bit scarier, but if you take your time and read through what is output, you will again find that the information is helpful in finding the problem in your code. After all, the purpose of the error message is to help the user find a problem :)."]},{"cell_type":"code","source":["#try and fix the code below:\n","def convert_wind_speed(speed):\n","    return speed * 1000 / 3600\n","\n","wind_speed_km = 30\n","wind_speed_ms = convert_wind_speed(wind_speed_km)\n","\n","print(f'A wind speed of {wind_speed_km} km/hr is {wind_speed_ms} m/s.)"],"metadata":{"id":"p8dcoBnJkDmw"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["#@title Click below to show fixed code\n","#try and fix the code below:\n","def convert_wind_speed(speed):\n","    return speed * 1000 / 3600\n","\n","wind_speed_km = 30\n","wind_speed_ms = convert_wind_speed(wind_speed_km)\n","\n","print(f'A wind speed of {wind_speed_km} km/hr is {wind_speed_ms} m/s.')"],"metadata":{"cellView":"form","id":"I8Vf0iblkLW0"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"1kjQdmRUh5CO"},"source":["### Common errors and exceptions\n","\n","Now that we have some idea of how to read an error message, let's have a look at a few different types of common Python exceptions that are displayed for different program errors.\n","\n","#### IndexErrors\n","\n","An `IndexError` occurs when you attempt to reference a value with an index outside the range of values.\n","We can easily produce an `IndexError` by trying to access the value at index 5 in the following list of cities: `cities = ['Paris', 'Berlin', 'London']`."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"MqAKhFM0h5CO"},"outputs":[],"source":["cities = ['Paris', 'Berlin', 'London']"]},{"cell_type":"code","execution_count":null,"metadata":{"tags":["raises-exception"],"id":"Gvv1faNEh5CP"},"outputs":[],"source":["cities[5]"]},{"cell_type":"markdown","metadata":{"id":"ayvFl4Csh5CP"},"source":["Here we get the rather clear error message that the index used for the list `cities` is out of the range of index values for that list. Our list only has three elements - and because of zero indexing, we access the third element with `cities[2]` (or, to be safer, `cities[-1]`)"]},{"cell_type":"markdown","metadata":{"id":"drag5oIuh5CQ"},"source":["#### NameErrors\n","\n","A `NameError` occurs when you reference a variable that has not been defined. We can produce a `NameError` by trying `station_id = stations[1]`."]},{"cell_type":"code","execution_count":null,"metadata":{"tags":["raises-exception"],"id":"Y6jFRPB1h5CQ"},"outputs":[],"source":["station_id = stations[1]"]},{"cell_type":"markdown","metadata":{"id":"SzGK4qJPh5CQ"},"source":["In this instance we receive a `NameError` because the list `stations` has not been defined, and we're thus not able to access a value in that list. You often get these when you open notebook you have been working on before and haven't executed all of the cells."]},{"cell_type":"markdown","metadata":{"id":"rhf43dzzh5CR"},"source":["#### IndentationErrors\n","\n","An `IndentationError` is raised whenever a code block is expected to be indented and is either not, or is indented inconsistently. Let's consider two examples below."]},{"cell_type":"code","execution_count":null,"metadata":{"tags":["raises-exception"],"id":"UD_e1ykGh5CR"},"outputs":[],"source":["for city in cities:\n","    city = city + ' is a city in Europe'\n","  print(city)"]},{"cell_type":"code","execution_count":null,"metadata":{"tags":["raises-exception"],"id":"o_sewL6Qh5CR"},"outputs":[],"source":["for city in cities:\n","city = city + ' is a city in Europe'\n","print(city)"]},{"cell_type":"markdown","metadata":{"id":"ywGT9-aDh5CR"},"source":["In both of the examples above, an `IndentationError` is raised.\n","* In the first case, the indentation level is inconsistent;\n"," * ***either*** the `print(city)` statement is indented by 4 spaces - in which case it part of the `for` loop,\n","  * ***or*** it is not indented at all - in which case it is executed after the `for` loop has completed.\n","\n","* In case two, indentation is expected in the statement following a `for` statement.\n","\n","##Check your understanding\n","\n","Edit the two code cells below to fix the indentation errors:"]},{"cell_type":"code","source":["for city in cities:\n","    city = city + ' is a city in Europe'\n","  print(city)"],"metadata":{"id":"3lITrE6zk7Fz"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["for city in cities:\n","city = city + ' is a city in Europe'\n","print(city)"],"metadata":{"id":"fbYYkZ2Sk9A2"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"YXVkftmWh5CS"},"source":["#### TypeErrors\n","\n","A `TypeError` is raised whenever two incompatible data types are used together. For example, if we try to divide a character string by a number or add a number to a boolean variable, a `TypeError` will be raised."]},{"cell_type":"code","execution_count":null,"metadata":{"tags":["raises-exception"],"id":"xN_pd6zqh5CS"},"outputs":[],"source":["cities[0] / 5"]},{"cell_type":"markdown","metadata":{"id":"d_Kgnno7h5CS"},"source":["In this case, the `TypeError` is because it is not possible to divide a character string by a number."]},{"cell_type":"markdown","metadata":{"id":"dubnewsuh5CS"},"source":["#### Other kinds of errors\n","\n","There are certainly [other kinds of errors and exceptions in Python](https://docs.python.org/3/tutorial/errors.html), but this list comprises those you're most likely to encounter.\n","As you can see, knowing the name of each error can be helpful in trying to figure out what has gone wrong, and knowing what these common error types mean will save you time trying to fix your programs."]},{"cell_type":"markdown","metadata":{"id":"fhTDDyoPh5CS"},"source":["### More information on errors\n","\n","You can find a bit more information about reading error messages on the [Software Carpentry](https://swcarpentry.github.io/python-novice-inflammation/09-errors/index.html) and [Python Software Foundation](https://docs.python.org/3/tutorial/errors.html) webpages.\n","\n","Also, Python 3.10 was just released in October 2021. Among the changes in this release are [improvements in the error messages](https://docs.python.org/3.10/whatsnew/3.10.html#better-error-messages) that are generated for many of the cases above. We will not be using Python 3.10 in the course, but you can feel free to test it out if you like."]}],"metadata":{"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.10"},"colab":{"provenance":[]}},"nbformat":4,"nbformat_minor":0}